version: "3.4"
services:
  logs:
    image: gerchardon/docker-logio
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: -h logio -n docker
    depends_on:
      - logio
  logio:
    image: temal/logio-server
    ports:
    - 28777:28777
    - 28778:28778